# Generated by Django 5.2.1 on 2026-05-16 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDevice',
            fields=[
                ('device_id', models.CharField(help_text='Unique device identifier (e.g. phone number)', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable device name', max_length=255)),
                ('device_type', models.CharField(default='modem', help_text='Device type (modem, gateway, etc.)', max_length=64)),
                ('api_key_hash', models.CharField(blank=True, help_text='SHA-256 hash of API key', max_length=64)),
                ('registration_token_hash', models.CharField(blank=True, help_text='SHA-256 hash of one-time registration token', max_length=64)),
                ('registration_token_expires_at', models.DateTimeField(blank=True, help_text='Registration token expiry time', null=True)),
                ('mqtt_client_id', models.CharField(blank=True, help_text='MQTT client ID for this device', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional device metadata')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=16)),
                ('is_available', models.BooleanField(default=False, help_text='Device is currently online/reachable')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last authentication time', null=True)),
                ('max_recipients_per_request', models.PositiveSmallIntegerField(default=50, help_text='Max recipients per SMS send request')),
                ('daily_sms_limit', models.PositiveIntegerField(default=500, help_text='Daily SMS sending limit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='external_de_status_a3137d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SmsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, help_text='Unique request identifier', max_length=32, unique=True)),
                ('recipients', models.JSONField(help_text='List of recipient phone numbers')),
                ('message', models.TextField(help_text='SMS message text')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_requests', to='external_device.externaldevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsRecipientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=16)),
                ('message_id', models.CharField(blank=True, help_text='External device message ID', max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_statuses', to='external_device.smsrequest')),
            ],
            options={
                'ordering': ['phone_number'],
            },
        ),
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, help_text='External device message ID', max_length=255, unique=True)),
                ('sender', models.CharField(db_index=True, help_text='Message sender phone number', max_length=64)),
                ('body', models.TextField(help_text='Message body')),
                ('received_at', models.DateTimeField(help_text='When the device received the message')),
                ('ack_sent', models.BooleanField(default=False, help_text='ACK has been sent to device')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbox_messages', to='external_device.externaldevice')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['device', '-received_at'], name='external_de_device__ff6b07_idx'), models.Index(fields=['-received_at'], name='external_de_receive_f1b105_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='smsrequest',
            index=models.Index(fields=['device', '-created_at'], name='external_de_device__5901fc_idx'),
        ),
        migrations.AddIndex(
            model_name='smsrequest',
            index=models.Index(fields=['status', '-created_at'], name='external_de_status_12641a_idx'),
        ),
        migrations.AddIndex(
            model_name='smsrecipientstatus',
            index=models.Index(fields=['request', 'phone_number'], name='external_de_request_461294_idx'),
        ),
    ]
