# Generated by Django 5.2.1 on 2026-05-17 16:29

import apps.external_device.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_device', '0003_hidishelink_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hidishelinkdevice',
            name='api_url',
            field=models.CharField(default=apps.external_device.models.default_hidishelink_api_url, help_text='Base URL only (no trailing path), e.g. http://192.168.1.77:5201', max_length=512),
        ),
        migrations.CreateModel(
            name='DeviceHealthTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_app', models.CharField(blank=True, help_text='Timestamp string from payload', max_length=64)),
                ('app_version', models.CharField(blank=True, max_length=128)),
                ('battery_level', models.SmallIntegerField(blank=True, null=True)),
                ('network_type', models.CharField(blank=True, max_length=32)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_telemetry_rows', to='external_device.externaldevice')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['device', '-received_at'], name='external_de_device__998a3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to='external_device.externaldevice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'revoked_at', 'expires_at'], name='external_de_device__f8b55e_idx')],
            },
        ),
    ]
