# Generated by Django 5.0.14 on 2026-05-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundSms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mm_path', models.CharField(blank=True, max_length=512)),
                ('modem_index', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('to_number', models.CharField(db_index=True, max_length=64)),
                ('text', models.TextField()),
                ('state', models.CharField(choices=[('created', 'Created'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='created', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundSms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mm_path', models.CharField(max_length=512, unique=True)),
                ('modem_index', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('from_number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('text', models.TextField(blank=True)),
                ('mm_state', models.CharField(blank=True, max_length=64)),
                ('smsc', models.CharField(blank=True, max_length=64)),
                ('modem_timestamp_raw', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'from_number'], name='sms_inbound_created_c29893_idx')],
            },
        ),
    ]
