# Generated by Django 5.0.14 on 2026-05-16 16:58

import apps.sms.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundsms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='outboundsms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='outboundsms',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='outboundsms',
            name='to_number',
            field=models.CharField(db_index=True, max_length=64, validators=[apps.sms.validators.sms_destination_validator]),
        ),
        migrations.AddIndex(
            model_name='outboundsms',
            index=models.Index(fields=['state', '-created_at'], name='sms_outboun_state_9acca9_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundsms',
            index=models.Index(fields=['modem_index', '-created_at'], name='sms_outboun_modem_i_f5a41b_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundsms',
            index=models.Index(fields=['-created_at'], name='sms_outboun_created_7112ed_idx'),
        ),
    ]
